In [ ]:
!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.78.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.2.25)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [2]:
import tensorflow as tf
print(tf.__version__)

2.19.0

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
dataset=pd.read_csv('Churn_Modelling.csv')
dataset.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
X=dataset.iloc[:,3:13]
Y=dataset.iloc[ : ,13]

In [7]:
# feature engineering

In [8]:
geography=pd.get_dummies(X['Geography'],drop_first=True).astype(int)
gender=pd.get_dummies(X['Gender'],drop_first=True).astype(int)

In [9]:
X=X.drop(['Geography','Gender'],axis=1)

In [10]:
X=pd.concat([X,gender,geography],axis=1)

In [11]:
X.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Male,Germany,Spain
0,619,42,2,0.00,1,1,1,101348.88,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1
2,502,42,8,159660.80,3,1,0,113931.57,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1

In [12]:
#train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [13]:
#scaling is required
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [14]:
x_train.shape

(8000, 11)

In [15]:
## creating ANN

In [19]:
from tensorflow.keras.models import Sequential  #used to do forward and backward passes
from tensorflow.keras.layers import Dense        #used to create input layer, hidden layer, output layer
from tensorflow.keras.layers import LeakyReLU,ReLU,PReLU,ELU  #activation functions
from tensorflow.keras.layers import Dropout     #to reduce overfitting

In [20]:
#initialize ANN
classifier=Sequential()

In [22]:
#create the input layer
classifier.add(Dense(units=11,activation='relu'))

In [24]:
#creating hidden layer 1
classifier.add(Dense(units=7,activation='relu'))

In [25]:
#creating hidden layer 2
classifier.add(Dense(units=6,activation='relu'))

In [26]:
#output layer
classifier.add(Dense(1,activation='sigmoid'))

In [33]:
#we will compile the ann
classifier.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])

In [32]:
#if you want to change the learning rate
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)

In [38]:
from tensorflow.keras.callbacks import EarlyStopping

In [41]:
early_stopping=EarlyStopping(
    monitor="val_loss",
    min_delta=0.0001,
    patience=20,
    verbose=1,
    mode="auto",
    baseline=None,
    restore_best_weights=False,
    start_from_epoch=0,
)

In [42]:
#train the ann
model_history=classifier.fit(x_train,y_train,validation_split=0.33,batch_size=10,epochs=1000,callbacks=early_stopping)

Epoch 1/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8604 - loss: 0.3277 - val_accuracy: 0.8504 - val_loss: 0.3599
Epoch 2/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8611 - loss: 0.3326 - val_accuracy: 0.8569 - val_loss: 0.3602
Epoch 3/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.8659 - loss: 0.3257 - val_accuracy: 0.8573 - val_loss: 0.3634
Epoch 4/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.8617 - loss: 0.3368 - val_accuracy: 0.8531 - val_loss: 0.3604
Epoch 5/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8600 - loss: 0.3302 - val_accuracy: 0.8546 - val_loss: 0.3611
Epoch 6/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8674 - loss: 0.3275 - val_accuracy: 0.8508 - val_loss: 0.3621
Epoch 7/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.8665 - loss: 0.3293 - val_accuracy: 0.8470 - val_loss: 0.3752
Epoch 8/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8650 - loss: 0.3249 - val_accuracy: 0.8576 - val_loss: 0.3631
Epoch 9/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8607 - loss: 0.3317 - val_accuracy: 0.8527 - val_loss: 0.3653
Epoch 10/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8603 - loss: 0.3271 - val_accuracy: 0.8470 - val_loss: 0.3756
Epoch 11/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8622 - loss: 0.3252 - val_accuracy: 0.8523 - val_loss: 0.3613
Epoch 12/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.8588 - loss: 0.3274 - val_accuracy: 0.8557 - val_loss: 0.3566
Epoch 13/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8612 - loss: 0.3332 - val_accuracy: 0.8584 - val_loss: 0.3678
Epoch 14/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8645 - loss: 0.3290 - val_accuracy: 0.8595 - val_loss: 0.3591
Epoch 15/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8517 - loss: 0.3469 - val_accuracy: 0.8489 - val_loss: 0.3685
Epoch 16/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.8578 - loss: 0.3343 - val_accuracy: 0.8565 - val_loss: 0.3664
Epoch 17/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.8631 - loss: 0.3307 - val_accuracy: 0.8482 - val_loss: 0.3634
Epoch 18/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8708 - loss: 0.3244 - val_accuracy: 0.8542 - val_loss: 0.3706
Epoch 19/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8647 - loss: 0.3186 - val_accuracy: 0.8478 - val_loss: 0.3719
Epoch 20/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8719 - loss: 0.3230 - val_accuracy: 0.8523 - val_loss: 0.3653
Epoch 21/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8679 - loss: 0.3232 - val_accuracy: 0.8573 - val_loss: 0.3618
Epoch 22/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8733 - loss: 0.3067 - val_accuracy: 0.8557 - val_loss: 0.3742
Epoch 23/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8737 - loss: 0.3113 - val_accuracy: 0.8538 - val_loss: 0.3649
Epoch 24/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8625 - loss: 0.3236 - val_accuracy: 0.8554 - val_loss: 0.3683
Epoch 25/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8639 - loss: 0.3195 - val_accuracy: 0.8523 - val_loss: 0.3738
Epoch 26/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8609 - loss: 0.3207 - val_accuracy: 0.8557 - val_loss: 0.3756
Epoch 27/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8702 - loss: 0.3205 - val_accuracy: 0.8550 - val_loss: 0.3682
Epoch 28/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8711 - loss: 0.3177 - val_accuracy: 0.8546 - val_loss: 0.3890
Epoch 29/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8676 - loss: 0.3202 - val_accuracy: 0.8554 - val_loss: 0.3692
Epoch 30/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8698 - loss: 0.3179 - val_accuracy: 0.8546 - val_loss: 0.3661
Epoch 31/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8756 - loss: 0.3116 - val_accuracy: 0.8542 - val_loss: 0.3732
Epoch 32/1000
536/536 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8610 - loss: 0.3263 - val_accuracy: 0.8531 - val_loss: 0.3843
Epoch 32: early stopping

In [43]:
y_pred=classifier.predict(x_test)
y_pred=(y_pred>0.5)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

In [46]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[1511,   84],
       [ 195,  210]])

In [47]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,y_pred)
acc

0.8605

In [48]:
model_history.history.keys()      #focused terms

dict_keys(['accuracy', 'loss', 'val_accuracy', 'val_loss'])

In [49]:
classifier.get_weights()

[array([[-0.46196198,  0.4060736 ,  1.1992557 ,  0.19295731, -0.3742874 ,
          0.45112127,  0.64182824, -0.16918091,  0.30328074,  0.77025247,
          0.64162   ],
        [ 1.6099463 , -3.1801426 , -0.90894556, -1.3443316 , -0.48597354,
         -3.2527864 , -0.16513452,  2.5669951 ,  1.2001034 , -1.091983  ,
          0.5239059 ],
        [-0.5898369 , -0.00907198, -0.10099142,  1.9744612 , -0.33291698,
         -0.20054433, -0.01676853, -0.41702503, -0.31029096,  1.6693649 ,
          0.16829453],
        [-2.0606306 ,  1.7961296 ,  1.652641  , -0.35453126, -1.2165575 ,
          0.49823087, -2.4077625 ,  0.41175795,  1.6971633 , -2.1888404 ,
          1.927496  ],
        [-3.6632571 ,  1.421492  , -0.9335873 ,  1.7364247 , -1.3252878 ,
          0.19507642,  2.5825574 ,  0.11905346,  3.2839112 , -0.57722944,
         -1.1839088 ],
        [-0.23214364,  0.02531472, -0.7738083 , -0.5990947 ,  1.5890439 ,
         -0.39642176,  0.22858849, -0.01193575, -0.42053086, -1.498499  ,
          0.61161363],
        [-1.9739345 , -0.6224656 , -2.2234151 ,  0.9814959 ,  0.36662355,
         -0.8516357 , -0.1584436 ,  1.8439649 , -1.0541439 ,  1.1104813 ,
          0.2581056 ],
        [ 0.5835996 ,  1.1604468 ,  0.4850684 ,  0.7029139 ,  0.67810476,
         -0.25800678, -0.03225432,  0.29913214,  0.01169201,  0.00463541,
         -0.11452841],
        [-0.25550735,  1.5163181 ,  0.1834934 ,  1.4829208 , -1.3936197 ,
          0.18350807, -0.01552397,  0.58009064, -0.14599766,  3.013642  ,
         -1.0614817 ],
        [ 0.78438026, -1.0433068 ,  0.7005557 , -1.1312883 ,  2.7025805 ,
         -0.80325985,  2.4379973 , -0.16534959, -0.19029218, -0.22264242,
          1.303895  ],
        [-0.8105576 ,  0.17401408, -0.02124001, -0.01915703, -0.31925148,
         -0.61138815,  0.2897178 , -0.03150243,  0.11759739, -0.5148786 ,
         -1.2080755 ]], dtype=float32),
 array([-0.7661841 , -1.5794739 , -1.6428548 , -2.115015  , -2.2064762 ,
         3.3641665 , -0.74340194, -4.096815  , -2.2588627 , -0.02910488,
        -2.8245633 ], dtype=float32),
 array([[ 1.0790669 ,  0.34466282, -0.37852463, -3.660345  ,  1.6278166 ,
         -3.3039305 ,  0.0721135 ],
        [-1.7448041 ,  1.6466755 ,  0.21835442, -1.253683  , -2.8729568 ,
          0.5005458 ,  1.0753372 ],
        [ 0.47679502, -1.7117535 , -0.51542735, -2.1762521 , -0.5952224 ,
          0.8082719 , -1.0212168 ],
        [-0.23921566,  1.8379108 ,  0.9779481 ,  0.7205851 , -1.0256816 ,
         -4.1919913 , -1.7345701 ],
        [-1.8095784 , -2.7484407 , -0.74991673,  0.5124662 , -0.02836016,
         -3.868438  ,  0.3199295 ],
        [-3.3846211 , -1.7526299 , -0.81416255,  0.17042847, -0.7213028 ,
         -0.65935653,  0.8778817 ],
        [-0.10927011,  0.27427533,  0.6794569 ,  0.5456893 , -3.606713  ,
         -3.0829463 ,  0.5432911 ],
        [-3.528795  ,  2.0863254 , -1.5598116 , -0.31582734,  0.35421175,
          1.7032462 ,  0.36588693],
        [ 0.7065029 , -0.74767786,  1.9516819 , -2.7253256 , -0.19906229,
         -3.5415301 , -0.44424447],
        [ 0.57920825, -0.07779032, -2.636721  ,  0.65277076,  1.4996088 ,
         -3.3177502 ,  1.1649475 ],
        [ 0.24491118,  0.0344653 , -1.6236404 , -2.577694  ,  0.57838655,
         -0.2506157 , -1.5161723 ]], dtype=float32),
 array([ 0.44266266, -3.2711132 , -3.5122828 ,  1.7592361 ,  1.0036329 ,
        -0.08525657,  0.17786896], dtype=float32),
 array([[ 0.0299862 , -0.41061342, -0.74506885,  0.07528917,  0.84184915,
         -1.1682861 ],
        [-0.02347942,  1.5378783 ,  0.11684528,  0.3536645 , -1.030704  ,
         -0.20263511],
        [-0.11120877, -2.018866  , -0.70170414,  0.34207284,  1.3504212 ,
         -0.3802054 ],
        [-0.11695806,  0.82916224, -0.32414305, -0.69887096, -1.6905195 ,
          0.28704014],
        [-0.8587795 , -0.6759486 , -0.41979006, -1.4284513 ,  0.37766474,
         -2.9183369 ],
        [-0.5116181 , -0.87134737, -0.4519152 , -0.5019219 ,  0.5198554 ,
         -1.279417  ],
        [-0.74968123,  0.46471655, -0.95745033, -0.7809949 , -0.9281608 ,
          0.12697493]], dtype=float32),
 array([-0.6858686 ,  0.84252006, -1.1457182 , -3.3195765 ,  0.83535725,
         1.6039376 ], dtype=float32),
 array([[ 0.48782456],
        [-0.3258422 ],
        [ 0.17490242],
        [ 0.11974756],
        [ 0.36119983],
        [-0.32656333]], dtype=float32),
 array([-1.1079178], dtype=float32)]